### PR TITLE
Added pcr and vaccination

### PR DESCRIPTION
**Pull request by rstager**
Added pcr testing and vaccination schedule.

### CODE REVIEW

**Comment by StevenSchlotterbeck** [comment]
> image
> 
> They eventually become filled when they start moving:
> image

^ This was a bug that was fixed in a PR from me yesterday. It looks like merging will be fine -- these changes don't touch any of the visualization code.

**Comment by rstager** [comment]
I originally was doing a random sampling of the full population for PCR tests.  The reason that I changed is that a random sampling is better at controlling an outbreak than the repeated testing of a sub population (like we are doing for rapid test).  That meant that PCR looked better comparing the same testing rate for both PCR and rapid test.  It makes sense when you think about it, because only testing a sub population controls the outbreak in the sub population, but the outbreak can run free in the rest of the population.  That may be why 60% rapid testing is a magic number. If we have the outbreak controlled in 60% of the population, then we have effectively achieved herd immunity (60-70%) and the outbreak dies off.  So do we want to have random testing and option for PCR and/or rapid test?  I can make both available.

**Comment by daveselinger** [comment]
Well the “good news” is you’re doing an apples to apples which makes total sense. 

Pcr will cap out at 1% most likely given current constraints (lab space, manufacturing and complex oversight and regulation) so that is the most likely apples to apples — 60% vs 1%. 

The randomness I worry about less given those constraints. Does that seem ok?
If we hold pcr to 1% fixed we are pretty intensely handicapping it in a way that a reviewer would call bs on IMO. I’d rather be conservative from that standpoint...

Selly

Mobile-sent. Excuse typos pleez

**Comment by rstager** [comment]
OK Selly, so I think what you would like is the Rapid test to be interval based on a sub population, and PCR tests to be random testing? I think I will add random testing for Rapid Tests as an advanced parameter so you can compare apples to apples if you want. Does that make sense?

**Comment by daveselinger** [comment]
Yes perfect thanks. 

Mobile-sent. Excuse typos pleez

**Comment by daveselinger** [comment]
Pulled main up into this one.

**Pull request merged**
